### ISSUE TITLE
Support URLs in addition to file paths

### ISSUE THREAD

**Issue by terrybrash** [terrybrashaw/grifter#3]
At the moment, there's no nice way of adding an entirely online game to your library (like https://krunker.io). Grifter should support links in addition to files.

This would look something like this in grifter.toml:

```toml
[[games]]
path = 'https://krunker.io'
slug = 'krunker'
```
